backend:
  name: github
  repo: Slavik191/Slavik191.github.io
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - name: "scorecard"
      label: "Scorecard"
      file: "content/scorecard.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "text"}
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Tables'
          name: "tables"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - label: "Table" 
              name: "table" 
              widget: "list"
              fields:
                - { label: "Scorecard Attribute", name: "scorecard-attribute", widget: "string"}
                - { label: "Category", name: "category", widget: "string"}
                - label: "Self-Assessment"
                  name: "self-assessment" 
                  widget: "select" 
                  options: ["Good", "Okay", "Needs improvement"]
                - { label: "Comments", name: "comments", widget: "md"}
            
            
