backend:
  name: github
  repo: Slavik191/Slavik191.github.io
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - name: "scorecard"
      label: "Scorecard"
      file: "content/scorecard.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "text"}
        - { label: "Body", name: "body", widget: "markdown"}
