backend:
  name: github
  repo: Slavik191/Slavik191.github.io
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
show_preview_links: false
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - name: "scorecard"
      label: "Scorecard"
      description: "Scorecard page"
      file: "content/scorecard.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "text"}
        - { label: "Body", name: "body", widget: "markdown", modes: ["rich_text"], buttons: ["heading-two", "link"], editor_components: ["sidenote"] }
        # - { label: "Collapsible Note", name: "Collapsible Note", widget: "markdown"}
        # - label: 'Section'
        #   name: "section"
        #   widget: list
        #   fields:
        #     - { label: "Title", name: "title", widget: "string"}
        #     - { label: "Description", name: "description", widget: "markdown"}
        #     - label: "Table" 
        #       name: "table"
        #       label_singular: "row"
        #       widget: "list"
        #       fields: 
        #         - { label: "Scorecard Attribute", name: "scorecard-attribute", widget: "string"}
        #         - name: categories
        #           label: Categories
        #           widget: categories
        #           separator: __
        #         - label: "Self-Assessment"
        #           name: "self-assessment" 
        #           widget: "select" 
        #           options: ["Good", "Okay", "Needs improvement"]
        #         - { label: "Comments", name: "comments", widget: "markdown"}
            
            
